org: maxwellnkendall
app: ckendall-commission-request-app
service: ckendall-commission-request
provider:
  name: aws
  runtime: nodejs12.x
  stage: TEST
  region: us-east-1
  memorySize: 128
  timeout: 300 # optional, in seconds, default is 6
functions:
  index:
    handler: index.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
  email:
    handler: index.handler
    events: 
      - http: 
          path: /send-email
          method: POST
          cors: true

